### PR TITLE
Create, alter, drop

### PR DESCRIPTION
**Pull request by akash-d-dev**
**Concepts covered -**
- Create,alter,drop

Video Link - combined -  https://drive.google.com/file/d/1vBr0siEkmRZmTCsrSLYshaZU8gEefCnW/view?usp=sharing

part 1 - https://drive.google.com/file/d/1yd9z3hc89gTrST9Cvom_gg_EuzTjemPe/view?usp=sharing
part 2 - https://drive.google.com/file/d/1-9nnks2hHER4X_aEWPArBu2ieC4qgAGd/view?usp=sharing

### CODE REVIEW

**Comment by th3c0d3br34ker** [comment]
hi @a5h101, please schedule a viva. the link is available in the wiki. Furthermore, the previous PR was merged with out approval. lets address this point in the viva as well.

thanks.

**Comment by akash-d-dev** [comment]
> hi @a5h101, please schedule a viva. the link is available in the wiki. Furthermore, the previous PR was merged with out approval. lets address this point in the viva as well.
> 
> thanks.

I merged the PR after getting the scores.

**Comment by th3c0d3br34ker** [comment]
as per viva discussion please re-submit with the updated self-viva.

re-submit on kalvium.community as well.

**Comment by akash-d-dev** [comment]
> as per viva discussion please re-submit with the updated self-viva.
> 
> re-submit on kalvium.community as well.

Explanation - https://drive.google.com/file/d/1BVCxuP_qjGPUFtpJb0Y50_HCGkVoKf6H/view?usp=sharing

**Comment by th3c0d3br34ker** [comment]
thanks @a5h101, this PR is satisfactory for `DDL commands`.

please go ahead and merge this PR.

**Review by th3c0d3br34ker — APPROVED** [review]

**Pull request merged**
