### PR TITLE
Schema, ERD added

### PR DESCRIPTION
**Pull request by akash-d-dev**

### CODE REVIEW

**Comment by th3c0d3br34ker** [comment]
hey @a5h101, please attach a loom video explaining the diagram and the schema. 

please avoid using google drive to share links. 

consider re-submitting once you format for submission is correct.

**Comment by akash-d-dev** [comment]
> hey @a5h101, please attach a loom video explaining the diagram and the schema.
> 
> please avoid using google drive to share links.
> 
> consider re-submitting once you format for submission is correct.

okay

**Comment by akash-d-dev** [comment]
Explanation Video - https://drive.google.com/file/d/1UicE85yrFO7K57mZPFU4GSg9J596nLjs/view?usp=sharing

**Review by th3c0d3br34ker — COMMENTED** [review]
thanks @a5h101 for you submission.

The cardinality and ordinality is missing in the ERD.

I am unable understand the `UserRegistration` entity, can you please provide more context on that? or you may book a viva slot. (link is available in the wiki).

thanks.

**Comment by anilgulecha** [comment]
Was viva conducted for this pls?

**Comment by akash-d-dev** [comment]
I got the scores, so I merged the PR.

**Pull request merged**
